### ISSUE TITLE
refactor the dev data model to be in a the big user data model

### ISSUE THREAD

**Issue by nourabousoha** [chingu-voyage3/bears-18#9]
the dev data model must to be included to a user data model that include devs , project owners and admins a role attribute will differentiate the different users  do you agree team if yes i will handle the change

**Comment by jprogdev14** [comment]
Correct me if I'm wrong, will all data such as username's and passwords from all parties be in one single collection, and then just be differentiated through roles? If that's the case, it might not be a bad idea. For development and early productions versions, this will make it easier to fetch data without having to switch collections.

**Comment by nourabousoha** [comment]
OK @jprogdev14  thanks I'll work on it
